version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: parenthq-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=null
        - MYSQL_DATABASE=parenthq
        - MYSQL_USER=root
        - MYSQL_PASSWORD=null
      ports:
        - "8002:3306"

    redis:
      container_name: redis
      image: redis
      ports:
        - "8003:6379"
      volumes:
        - ../data/redis:/data
      entrypoint: redis-server --appendonly yes
    webserver:
      image: nginx:alpine
      container_name: parenthq-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: parenthq-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

