version: "3.8"
services:
  parenthq_app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - parenthq_db
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: blog-app
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: parenthq
      DB_PORT: 3306
    networks:
      - app_network

  parenthq_nginx:
    build:
      context: ./docker-nginx/.
    volumes:
      - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: parenthq_app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - parenthq_app
    networks:
      - app_network
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
  parenthq_db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: parenthq
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - "./storage/db-data:/var/lib/mysql"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
